{{ if (.Values.frontend.hpa_enabled) }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-frontend"
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: "{{ .Release.Name }}-frontend"
  minReplicas: {{ .Values.frontend.minReplicas }}
  maxReplicas: {{ default 1 .Values.frontend.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
{{- end }}
