env: staging

domainName: dr-test-app.app.artifactstaging.com
ingressClass: nginx-ingress
certIssuer: letsencrypt
certSecret: dr-test-app

static:
  - foo.app.artifactstaging.com
  - bar.app.artifactstaging.com

frontend:
  - bin.app.artifactstaging.com
  - baz.app.artifactstaging.com

fastly: app.artifactstaging.com.global.prod.fastly.net

hpa_enabled: false
replicas: 1

labels:
  app: dr-test-app

image:
  repository: 966326147313.dkr.ecr.us-west-2.amazonaws.com/dr-test-app
  tag: latest

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

port: "9090"

envConfig:
  ENVIRONMENT: staging
